[package]
name = "readlion"
version = "0.1.0"
authors = ["Stephen Weeks <tene@allalone.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shell-engine = { path = "../shell-engine" }
mortal = "0.2.2"